language: php
php:
- '7.1'
- '7.2'
- '7.3'
- '7.4'
before_script:
- |
  echo "TRAVIS_PHP_VERSION:" $TRAVIS_PHP_VERSION;
  php -v;
  php -r 'echo "PHP: ".PHP_VERSION."\n";';
  if [ $(echo "$TRAVIS_PHP_VERSION <= 7.1" | bc -l) -eq 1 ]; then
    echo using PHPUnit 7.5.9
    curl -sSfL -o ~/.phpenv/versions/$TRAVIS_PHP_VERSION/bin/phpunit https://phar.phpunit.de/phpunit-7.5.9.phar;
  fi
- travis_retry composer self-update
- travis_retry composer install --no-interaction --prefer-source --no-dev
script:
- phpunit -c phpunit.xml
env:
  global:
  - secure: LGXc3k+Iy8nJbA+xllNk6FbGdb6i4tINU/gCfFlVIamVTQW4IGCfPajPBj5ulsr75YKPoeeya21zwr9nnq3nmBwCppVQHiWBBZDCnaFp8BTTyd6K3q8pJyjWikHJah2UvBUB+XbpzDv7a426tKha2rZWwnBnSnjxrRg0FRNkKvBbm6TvFPHrxNc6RPXpjk3AbRfKgWhFsPJodt4hEU2Pl01HC7eBSs9SgaP6cq5dnx078y4kJVGL10o4N0fGpMPrm7T+NKBukz0FxvqYW7U/Jxmzh+qBRNdx7KymRPBEPNi9ULW5tFFNMwICcmpVIoeoYPV04jNFT+X6A6cgc5jHivAnhKeDsldiGMKuCq24a43P3LmLpLaTs+CxYI/bw9izoSPPQuui2pBDuUwPlvJfqDRTDRGYGFdpEcTofjYkvz1D5tcNx3HkoTOBnXsdsV1pHKYgmlglnx30gBJLIw+sSd1T6Bpuub3qhw0932wfZf7MYwJBiJnS6kESWwmstCTVhZE5aaw/NCyXuS4PVvomxBkbJoh8jNpIKf47mLGPmB++/hGQhNjM9scMO/4EWcu+gqDgcSF8Erh3HyVcQ5WuCwukEZyq8FyaAcJLQucArOFb2IbCH02xIh/pJLQupr4WbJZdx3CqF9F4SMa8BxHlz3zlL598/6emLT6+Onx5Q20=
